character/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.CharacterListView.as_view(), name='character_list'),
    path('character_add/', views.character_add, name='character_add'),
    path('character_edit/', views.character_edit, name='character_edit'),
    path('character_update_gm/<int:character_id>/', views.character_update_gm, name='character_update_gm'),
    path('character_view/<int:pk>/', views.CharacterDetailView.as_view(), name='character_view'),
]

urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
]

character/models.py
from django.conf import settings
from django.db import models

from empires.stdfields.fields import EnumCharField

from alchemy.models import AlchemySpecialty
from charclass.models import CharClass
from character.enums import chartype
from equipment.enums import armourlocation, equipmentsource
from equipment.models import ArmourType, Equipment
from generic.enums import handed
from magic.models import Deity, MagicSchool, MagicSubSchool
from player.models import Player
from race.models import Race, SubRace
from skill.models import Skill

User = settings.AUTH_USER_MODEL


class Character(models.Model):
    name = models.CharField(unique=True, max_length=128)
    chartype = EnumCharField(
        'Character Type',
        choices=chartype.all(), max_length=chartype.max_length())
    player = models.ForeignKey(Player, models.SET_NULL, blank=True, null=True)
    race = models.ForeignKey(Race, models.RESTRICT)
    subrace = models.ForeignKey(
        SubRace, models.SET_NULL, blank=True, null=True)
    charclass = models.ForeignKey(CharClass, models.RESTRICT)
    deity = models.ForeignKey(Deity, models.SET_NULL, blank=True, null=True)
    event_count = models.PositiveSmallIntegerField(default=0)
    xp_earned = models.PositiveSmallIntegerField(default=10)
    xp_spent = models.PositiveSmallIntegerField(default=0)
    level = models.PositiveSmallIntegerField(default=1)
    death_count = models.PositiveSmallIntegerField(default=0)
    coin_iron = models.PositiveIntegerField(default=0)
    bank_iron = models.PositiveIntegerField(default=0)
    is_dead = models.BooleanField(default=False)

    class Meta:
        db_table = 'character'

    def __str__(self):
        return self.name

    def has_racial_skills(self):
        return self.race.name != 'Human' or self.subrace

    def skills_dict(self):
        skills_dict = {'base': {}, 'handed': {}}
        char_skills = self.character_skill_set.order_by(
            'skill__skilltype', 'skill__name')
        for char_skill in char_skills:
            skilltype = char_skill.skill.skilltype.name
            if skilltype not in skills_dict['base'].keys():
                skills_dict['base'][skilltype] = []
            if char_skill.level > 0:
                level = str(char_skill.level)
            else:
                level = ''
            skill_dict = {
                'id': char_skill.id, 'skill_id': char_skill.skill.id,
                'name': char_skill.skill.name, 'level': level}
            skills_dict['base'][skilltype].append(skill_dict)
            handed_skills = char_skill.character_skill_hand_set.all()
            if handed_skills.exists():
                skills_dict['handed'][char_skill.id] = {}
                for handed_skill in handed_skills:
                    skills_dict['handed'][char_skill.id][handed_skill.hand] = \
                        handed_skill.level
        return skills_dict

    def slots_dict(self):
        slots_dict = {}
        char_alchemy = self.character_alchemyslots_set.order_by(
            'level', 'specialty')
        if char_alchemy.exists():
            slots_dict['alchemy'] = []
            for alchemy in char_alchemy:
                alchemy_dict = {
                    'level': alchemy.level, 'specialty': alchemy.specialty,
                    'slots': alchemy.slots
                }
                slots_dict['alchemy'].append(alchemy_dict)
        char_spell = self.character_spellslots_set.order_by(
            'school', 'specialty', 'level')
        if char_spell.exists():
            slots_dict['spells'] = []
            for spell in char_spell:
                spell_dict = {
                    'school': spell.school, 'specialty': spell.specialty,
                    'level': spell.level, 'slots': spell.slots
                }
                slots_dict['spells'].append(spell_dict)
        return slots_dict


class CharacterArmourWorn(models.Model):
    character = models.ForeignKey(Character, models.RESTRICT)
    armourlocation = EnumCharField(
        choices=armourlocation.all(), max_length=armourlocation.max_length())
    armourtype = models.ForeignKey(ArmourType, models.RESTRICT)

    class Meta:
        db_table = 'character_armourworn'

    def __str__(self):
        return '{} {} - {}'.format(
            str(self.character),
            str(self.armourlocation), str(self.armourtype))


class CharacterEffects(models.Model):
    character = models.ForeignKey(Character, models.RESTRICT)
    effect = models.TextField()
    notes = models.TextField(blank=True, null=True)
    start_utc = models.DateTimeField(blank=True, null=True)
    end_utc = models.DateTimeField(blank=True, null=True)
    entered_by = models.ForeignKey(User, models.RESTRICT)
    entered_utc = models.DateTimeField()
    is_active = models.BooleanField()

    class Meta:
        db_table = 'character_effects'

    def __str__(self):
        return '{} Effect'.format(str(self.character))


class CharacterEquipment(models.Model):
    character = models.ForeignKey(Character, models.RESTRICT)
    equipment = models.ForeignKey(Equipment, models.RESTRICT)
    source = EnumCharField(
        choices=equipmentsource.all(),
        max_length=equipmentsource.max_length())
    notes = models.TextField(blank=True, null=True)
    acquired_utc = models.DateTimeField()
    lost_utc = models.DateTimeField(blank=True, null=True)
    entered_by = models.ForeignKey(User, models.RESTRICT)
    entered_utc = models.DateTimeField()

    class Meta:
        db_table = 'character_equipment'

    def __str__(self):
        return '{} {}'.format(str(self.character), str(self.equipment))


class CharacterShardXP(models.Model):
    assigned_to = models.ForeignKey(Character, models.RESTRICT)
    xp_assigned = models.PositiveSmallIntegerField()
    entered_by = models.ForeignKey(User, models.RESTRICT)
    entered_utc = models.DateTimeField()

    class Meta:
        db_table = 'character_shardxp'


    def __str__(self):
        return '{} {} - {}'.format(
            str(self.character), str(self.xp_assigned),
            self.entered_utc.strftime('%Y-%m-%d'))


class Character_Skill(models.Model):
    character = models.ForeignKey(Character, models.RESTRICT)
    skill = models.ForeignKey(Skill, models.RESTRICT)
    level = models.PositiveSmallIntegerField()

    class Meta:
        db_table = 'character_skill'
        unique_together = (('character', 'skill'),)

    def __str__(self):
        return '{} {} - {}'.format(
            str(self.character), self.skill.name, self.level)


class Character_Skill_Hand(models.Model):
    character_skill = models.ForeignKey(Character_Skill, models.RESTRICT)
    hand = EnumCharField(
        choices=handed.all(), max_length=handed.max_length())
    level = models.PositiveSmallIntegerField()

    class Meta:
        db_table = 'character_skill_hand'
        unique_together = (('character_skill', 'hand'),)

    def __str__(self):
        return '{} {} {} - {}'.format(
            str(self.character_skill.character),
            self.character_skill.skill.name, self.hand, self.level)


class Character_AlchemySlots(models.Model):
    character = models.ForeignKey(Character, models.RESTRICT)
    specialty = models.ForeignKey(
        AlchemySpecialty, models.SET_NULL, blank=True, null=True)
    level = models.PositiveSmallIntegerField()
    slots = models.PositiveSmallIntegerField()

    class Meta:
        db_table = 'character_alchemyslots'
        unique_together = (('character', 'specialty', 'level'),)

    def __str__(self):
        special = ''
        if self.specialty:
            special = ' - {}'.format(str(self.specialty))
        return '{} {} level {} - {}'.format(
            str(self.character), special, self.level, self.slots)


class Character_SpellSlots(models.Model):
    character = models.ForeignKey(Character, models.RESTRICT)
    school = models.ForeignKey(MagicSchool, models.RESTRICT)
    specialty = models.ForeignKey(
        MagicSubSchool, models.RESTRICT, blank=True, null=True)
    level = models.PositiveSmallIntegerField()
    slots = models.PositiveSmallIntegerField()

    class Meta:
        db_table = 'character_spellslots'
        unique_together = (('character', 'school', 'specialty', 'level'),)

    def __str__(self):
        return '{} {} {} level {} - {}'.format(
            str(self.character), self.school.name, self.specialty.name,
            self.level, self.slots)

skill/models.py
from django.db import models

from empires.stdfields.fields import EnumCharField

from charclass.models import CharClass
from race.models import Race, SubRace
from skill.enums import attacktype, skilltype


class SkillType(models.Model):
    name = models.CharField(unique=True, max_length=32)

    class Meta:
        db_table = 'skilltype'

    def __str__(self):
        return self.name


class RacialSkillType(models.Model):
    name = models.CharField(unique=True, max_length=32)

    class Meta:
        db_table = 'racialskilltype'

    def __str__(self):
        return self.name


class SpecialType(models.Model):
    attacktype = EnumCharField(
        choices=attacktype.all(), max_length=attacktype.max_length())
    name = models.CharField(unique=True, max_length=32)

    class Meta:
        db_table = 'attacktype'
        unique_together = (('attacktype', 'name'),)

    def __str__(self):
        return '{} {}'.format(self.name, self.attacktype)


class Skill(models.Model):
    name = models.CharField(max_length=256)
    skilltype = models.ForeignKey(SkillType, models.RESTRICT)
    multiple = models.PositiveSmallIntegerField()
    call = models.CharField(max_length=128, blank=True, null=True)
    description = models.TextField()

    class Meta:
        db_table = 'skill'
        unique_together = (('name', 'skilltype'),)

    def is_handed(self):
        return hasattr(self, 'handedskill')

    def __str__(self):
        return '{} - {}'.format(self.name, str(self.skilltype))


class AttackCost(models.Model):
    attack = models.ForeignKey(Skill, models.RESTRICT)
    level = models.PositiveSmallIntegerField(blank=True, null=True)
    charclass = models.ForeignKey(
        CharClass, models.SET_NULL, blank=True, null=True)
    xp_cost = models.PositiveSmallIntegerField()

    class Meta:
        db_table = 'attackcost'
        unique_together = (('attack', 'level', 'charclass'),)

    def __str__(self):
        level = ''
        cclass = ''
        if self.level:
            level = ' - {}'.format(str(self.level))
        if self.charclass:
            cclass = ' - {}'.format(str(self.charclass))
        return '{}{}{}'.format(str(self.skill), level, cclass)


class SkillCost(models.Model):
    skill = models.ForeignKey(Skill, models.RESTRICT)
    charclass = models.ForeignKey(
        CharClass, models.SET_NULL, blank=True, null=True)
    xp_cost = models.PositiveSmallIntegerField()

    class Meta:
        db_table = 'skillcost'
        unique_together = (('skill', 'charclass'),)

    def __str__(self):
        cclass = ''
        if self.charclass:
            cclass = ' - {}'.format(str(self.charclass))
        return '{}{}'.format(str(self.skill), cclass)


class Race_RacialSkillType(models.Model):
    race = models.ForeignKey(Race, models.RESTRICT)
    subrace = models.ForeignKey(
        SubRace, models.SET_NULL, blank=True, null=True)
    racialskilltype = models.ForeignKey(RacialSkillType, models.RESTRICT)
    group = models.IntegerField()

    class Meta:
        db_table = 'race_racialskilltype'
        unique_together = (('race', 'subrace', 'racialskilltype'),)

    def __str__(self):
        race = str(self.race)
        if self.subrace:
            race = '{} - {}'.format(str(self.subrace), race)
        return '{} - {}'.format(race, str(self.racialskilltype))


class Skill_RacialSkillType(models.Model):
    skill = models.ForeignKey(Skill, models.RESTRICT)
    racialskilltype = models.ForeignKey(RacialSkillType, models.RESTRICT)

    class Meta:
        db_table = 'skill_racialskilltype'
        unique_together = (('skill', 'racialskilltype'),)

    def __str__(self):
        return '{} - {}'.format(str(self.racialskilltype), self.skill.name)


class Attack_SpecialType(models.Model):
    attack = models.ForeignKey(Skill, models.RESTRICT)
    specialtype = models.ForeignKey(SpecialType, models.RESTRICT)

    class Meta:
        db_table = 'attack_specialtype'
        unique_together = (('attack', 'specialtype'),)

    def __str__(self):
        return '{} - {}'.format(str(self.specialtype), self.attack.name)


class HandedSkill(models.Model):
    skill = models.OneToOneField(Skill, models.RESTRICT)

    class Meta:
        db_table = 'handedskill'

    def __str__(self):
        return '{} (Hand)'.format(self.skill.name)

character/templates/character_list.html
{% extends extend %}

{% block character_active %}class="active"{% endblock %}

{% block title_text %}
Characters
{% endblock %}

{% load static %}
{% block extrahead %}
{{ block.super }}
{% endblock %}

{% block breadcrumbs %}
<li><a href="/empires">home</a></li>
<li><a href="{% url 'character_list' %}">characters</a></li>
{% endblock %}

{% block main_panel_layout %}
<div class="panel">
    <div class="panel-heading">
        <h4 class="panel-title">
            <i class="fa fa-user"></i> Characters
        </h4>
    </div>
    <div class="panel-body" id="id_character_list">
        {% if gm_view %}
            <a id="id_create_character" class="btn btn-success" href="{% url 'character_update_gm' 0 %}"><i class="fa fa-plus-circle"></i> add</a>
        {% endif %}
        <br/>
        <table id="id_tbl_characters" class="table table-striped">
            <thead>
                <tr>
                    {% if gm_view %}<th>Player</th>{% endif %}
                    <th>Name</th>
                    <th>Race</th>
                    <th>Class</th>
                </tr>
            </thead>
            <tbody>
                {% for character in object_list %}
                <tr>
                    {% if gm_view %}<td>{{ character.player }}</td>{% endif %}
                    <td><a href="{% url 'character_view' character.id %}">{{ character.name }}</a></td>
                    <td>{{ character.race }}{% if character.subrace %} ({{ character.subrace.name }}){% endif %}</td>
                    <td>{{ character.charclass }}</td>
                </tr>
                {% empty %}
                <tr>No existing characters</tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

character/templates/character_update_gm.html
{% extends extend %}

{% block character_active %}class="active"{% endblock %}

{% block title_text %}
{% if character %}Update{% else %}Add{% endif %} Character
{% endblock %}

{% load static %}
{% block extrahead %}
{{ block.super }}
{% endblock %}

{% block breadcrumbs %}
<li><a href="/empires">home</a></li>
<li><a href="{% url 'character_list' %}">characters</a></li>
{% if character %}
<li><a href="{% url 'character_update_gm' character.id %}">update {{ character.name }}</a></li>
{% else %}
<li><a href="{% url 'character_update_gm' 0 %}">add character</a></li>
{% endif %}
{% endblock %}

{% block main_panel_layout %}
<form method="post" id="id_character_update">
    {% csrf_token %}
    <div class="row">
	    <div class="col-md-3">
	        <div class="row">
                <div class="col-md-12"> 
					<div class="panel panel-np">
						<div class="panel-heading">
							<h4 class="panel-title">
								<i class="fa fa-stethoscope"></i> Base Character:
							</h4>
						</div>
						<div class="panel-body">
									{% csrf_token %}
							<div class="row">
                                {{ base_form }}
							</div>
				        </div>
				    </div>
				</div>
			</div>
			<div class="row">
                <div class="col-md-12 top_button">
                    <button id="id_btn_save" type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Save Character</button>
	                <a class="btn btn-default" href="{% block cancel_location %}{% url 'character_list' %}{% endblock cancel_location %}">
	                <i class="fa fa-times"></i> Cancel and return to Character List</a>
                </div>
            </div>
            <div class="row button_batting_bottom">
                <div class="col-md-12 ">  
                </div>
            </div>
		</div>
		<div class="col-md-9">  
		    <div class="panel panel-np">
		        <div class="panel-heading">
		            <h4 class="panel-title">
		                <i class="fa fa-broadcast-tower"></i> Skills
		            </h4>
		        </div>
		        <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Skill</th>
								<th>Hand</th>
								<th>Level</th>
                            </tr>
                        </thead>
                        <tbody>
                        {{ skill_formset.management_form }}
                        {% for skform in skill_formset %}
                            <tr>
                                <td class="{% if skform.skill.errors %}has-error{% elif skform.is_bound %}has-success{% endif %}">
                                    {{ skform.skill }}
		                            {% if skform.skill.errors %}
                                    <span class="help-block">
                                        {% for error in skform.skill.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </span>
                                    {% endif %}
                                </td>
		                        <td class="{% if skform.hand.errors %}has-error{% elif skform.is_bound %}has-success{% endif %}">
                                    {{ skform.hand }}
		                            {% if skform.hand.errors %}
                                    <span class="help-block">
                                        {% for error in skform.hand.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </span>
                                    {% endif %}
		                        </td>
		                        <td>
                                    {{ skform.level }}
                                </td>
		                    </tr>
					{% endfor %}
                        </tbody>
                    </table>
				</div>
			</div>
		    <div class="panel panel-np">
		        <div class="panel-heading">
		            <h4 class="panel-title">
		                <i class="fa fa-broadcast-tower"></i> Alchemy Slots
		            </h4>
		        </div>
		        <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Specialty</th>
								<th>Level</th>
								<th>Slots</th>
                            </tr>
                        </thead>
                        <tbody>
                        {{ alchemy_formset.management_form }}
                        {% for alform in alchemy_formset %}
                            <tr>
                                <td class="{% if alform.specialty.errors %}has-error{% elif alform.is_bound %}has-success{% endif %}">
                                    {{ alform.specialty }}
		                            {% if alform.specialty.errors %}
                                    <span class="help-block">
                                        {% for error in alform.specialty.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </span>
                                    {% endif %}
                                </td>
		                        <td>
                                    {{ alform.level }}
		                        </td>
		                        <td>
                                    {{ alform.slots }}
                                </td>
		                    </tr>
					{% endfor %}
                        </tbody>
                    </table>
				</div>
			</div>
		    <div class="panel panel-np">
		        <div class="panel-heading">
		            <h4 class="panel-title">
		                <i class="fa fa-broadcast-tower"></i> Spell Slots
		            </h4>
		        </div>
		        <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>School</th>
                                <th>Specialty</th>
								<th>Level</th>
								<th>Slots</th>
                            </tr>
                        </thead>
                        <tbody>
                        {{ spell_formset.management_form }}
                        {% for spform in spell_formset %}
                            <tr>
		                        <td>
                                    {{ spform.school }}
		                        </td>
                                <td class="{% if spform.specialty.errors %}has-error{% elif spform.is_bound %}has-success{% endif %}">
                                    {{ spform.specialty }}
		                            {% if spform.specialty.errors %}
                                    <span class="help-block">
                                        {% for error in spform.specialty.errors %}
                                            {{ error }}
                                        {% endfor %}
                                    </span>
                                    {% endif %}
                                </td>
		                        <td>
                                    {{ spform.level }}
		                        </td>
		                        <td>
                                    {{ spform.slots }}
                                </td>
		                    </tr>
					{% endfor %}
                        </tbody>
                    </table>
				</div>
			</div>
        </div>
    </div>
</form>
{% endblock %}

character/templates/character_view.html
{% extends extend %}

{% block character_active %}class="active"{% endblock %}

{% block title_text %}
View Character
{% endblock %}

{% load static %}
{% block extrahead %}
{{ block.super }}
{% endblock %}

{% block breadcrumbs %}
<li><a href="/empires">home</a></li>
<li><a href="{% url 'character_list' %}">characters</a></li>
<li><a href="{% url 'character_view' object.id  %}">{{ object.name }} details</a></li>
{% endblock %}

{% block main_panel_layout %}
<div id="details-panel" class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            <i class="fa fa-info-circle"></i> Character Details - {{ object.name }}
        </h3>
    </div>
    <div class="panel-body" id="id_character_details">
        {% if perms.character.change_character %}
            <a id="id_edit_character" class="btn btn-success" href="{% url 'character_update_gm' object.id %}"><i class="fa fa-pencil-square-o"></i> edit</a>
        {% endif %}
        <br/>
        <table class="table table-striped">
            {% if gm_view %}
            <tr>
                <td>Player: </td>
                <td>{{ object.player.name }}</td>
            </tr>
            {% endif %}
            <tr>
                <td>Name: </td>
                <td>{{ object.name }}</td>
            </tr>
            <tr>
                <td>Race: </td>
                <td>{% if object.subrace %}{{ object.subrace }}{% else %}{{ object.race }}{% endif %}</td>
            </tr>
            <tr>
                <td>Class: </td>
                <td>{{ object.charclass }}</td>
            </tr>
            <tr>
                <td>SKILLS</td>
                <td></td>
            </tr>
            {% for skill_type, skill_list in object.skills_dict.base.items %}
            <tr>
                <td>{{ skill_type }}</td>
                <td>
                    <table class="table table-striped">
                        <thead><th>skill</th><th>level</th></thead>
                        <tbody>
                            {% for skill in skill_list %}
                                {% if skill.id in object.skills_dict.handed %}
                                    {% for skill_id, hand_dict in object.skills_dict.handed.items %}
                                        {% if skill_id == skill.id %}
                                            {% for hand, level in hand_dict.items %}
                                                <tr>
                                                    <td>{{ skill.name }} - {{ hand }} hand</td>
                                                    <td>{{ level }}</td>
                                                </tr>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                <tr>
                                    <td>{{ skill.name }}</td>
                                    <td>{{ skill.level }}</td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </td>
            </tr>
            {% empty %}
            <tr><td>No skills</td></tr>
            {% endfor %}
            {% if 'alchemy' in object.slots_dict %}
            <tr>
                <td>ALCHEMY</td>
                <td>
                    <table class="table table-striped">
                        <thead><th>level</th><th>specialty</th><th>slots</th></thead>
                        <tbody>
                            {% for alchemy in object.slots_dict.alchemy %}
                            <tr>
                                <td>{{ alchemy.level }}</td>
                                <td>{% if alchemy.specialty %}{{ alchemy.specialty }}{% endif %}</td>
                                <td>{{ alchemy.slots }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>
            </tr>
            {% endif %}
            {% if 'spells' in object.slots_dict %}
            <tr>
                <td>SPELLS</td>
                <td>
                    <table class="table table-striped">
                        <thead><th>school</th><th>specialty</th><th>level</th><th>slots</th></thead>
                        <tbody>
                            {% for spell in object.slots_dict.spells %}
                            <tr>
                                <td>{{ spell.school }}</td>
                                <td>{% if spell.specialty %}{{ spell.specialty.name }}{% endif %}</td>
                                <td>{{ spell.level }}</td>
                                <td>{{ spell.slots }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>
            </tr>
            {% endif %}
        </table>
    </div>
</div>
{% endblock %}